config/routes.rb
Rails.application.routes.draw do

  root 'photos#index'

  get 'admin' => 'photos#new', as: :new_photo

  post 'admin' => 'photos#create', as: :photos

  get 'login' => 'sessions#new'

  post 'login' => 'sessions#create'

  delete 'logout' => 'sessions#delete'

  get 'tags/:tag' => 'tags#show', as: :tag

end

app/models/photo.rb
class Photo < ActiveRecord::Base

  acts_as_taggable
  mount_uploader :name, AvatarUploader

  validates :name, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  before_action do
    @photos = Photo.all.order('created_at desc').page(params[:page])
  end

  def index
  end

  def new
    unless current_user == nil
      @photo = Photo.new
    else
      redirect_to root_path, alert: 'Please login first.'
    end
  end

  def create
    @photo = Photo.new photo_params
    if @photo.save
      redirect_to root_path, notice: "Success!"
    else
      flash.now[:alert] = 'Fail!'
      render :new
    end
  end

  private

    def photo_params
      params.require(:photo).permit(:name, :tag_list)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(name: params[:name])
    if user && user.authenticate(params[:password])
      login user
      redirect_to new_photo_path
    else
      flash.now[:alert] = '👽'
      render :new
    end
  end

  def delete
    session.delete :name
    redirect_to root_path
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def show
    @photos = Photo.tagged_with("#{params[:tag]}").order('created_at desc').page(params[:page])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper

  def list_of_tags
    self.tag_list.each 
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper

  def login user
    session[:name] = user.name
  end

  def current_user
    @current_user ||= User.find_by(name: session[:name])
  end

  def authenticate_user
    @current_user = current_user
    if @current_user.nil?
      redirect_to login_path
    end
  end

end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/layouts/_login_form.html.erb
<!-- <h1>Login</h1>

<div class="row">

  <div class="col-md-6 col-md-offset-3">

    <%= form_for(:session, url: login_path) do |f| %>

      <%= f.text_field :name, class: 'form-control form-group', placeholder: 'Name' %>

      <%= f.password_field :password, class: 'form-control form-group', placeholder: 'Password' %>

      <%= f.submit 'Login', class: 'btn btn-success form-control', style: 'margin-bottom: .3em;' %>

    <% end %>

  </div>

</div> -->

<%= form_tag login_path, method: :post do %>

  <div class="form-group">
    <%= label_tag :name %>
    <%= text_field_tag :name, params[:name], class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label_tag :password %>
    <%= password_field_tag :password, "", class: "form-control"  %>
  </div>

  <div>
    <%= submit_tag "Sign in", class: "btn btn-primary" %>
  </div>

<% end %>

app/views/layouts/_nav.html.erb
<nav>

  <div class="row">

    <div class="nav navbar-default">

      <div class="container">

        <%= link_to 'Home', root_path %>

        <% if session[:name].present? %>

          <%= link_to 'Upload', new_photo_path, class: 'nav-element' %>
          <%= link_to 'Sign Out', logout_path, method: :delete, class: 'nav-element' %>

        <% else %>

          <%= link_to 'Sign In', login_path, class: 'nav-element' %>

        <% end %>

      </div>

    </div>

  </div>

</nav>

app/views/layouts/_photo_form.html.erb
<div class="row">

  <div class="col-md-6 col-md-offset-3" style='margin-top: 15%;'>

    <%= simple_form_for @photo do |f| %>

      <%= f.input_field :name, class: 'form-group' %>
      <%= f.input_field :tag_list, placeholder: 'Tags: separate by commas', class: 'form-control form-group' %>
      <%= f.submit 'Upload', class: 'btn btn-primary' %>

    <% end %>

  </div>

</div>

app/views/layouts/_photos.html.erb
<% @photos.each do |photo| %>

  <div class="photo" style="float: left;">

    <%= image_tag photo.name.url(:thumb) %>

    <div class="clearfix"></div>

    Tags: <% photo.tag_list.each do |tag| %>

      <%= link_to tag, tag_path(tag: tag) %>

    <% end %>

  </div>

<% end %>

<div class="clearfix"></div>

<%= paginate @photos %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Photo Uploader</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container-fluid">

    <%= render 'layouts/nav' %>

  </div>

  <div class="container">

    <% if notice %>
      <div class="alert alert-success"><%= notice %></div>
    <% end %>

    <% if alert %>
      <div class="alert alert-danger"><%= alert %></div>
    <% end %>

    <%= yield %>

  </div>

</body>
</html>

app/views/photos/index.html.erb
<h1>Photos</h1>

<%= render 'layouts/photos' %>

app/views/photos/new.html.erb
<%= render 'layouts/photo_form' %>

app/views/tags/show.html.erb
<h1>Tag <%= params[:tag] %></h1>

<%= render 'layouts/photos' %>